apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: test-mc
  namespace: default
providerSpec:
  # Required: STACKIT machine type (e.g., "c1.2", "m1.4", "g1.8")
  machineType: "c1.2"

  # Required: UUID of the OS image to use
  imageId: "550e8400-e29b-41d4-a716-446655440000"

  # Optional: User-defined labels for the server
  # MCM will automatically add standard labels (machine name, class, role)
  labels:
    environment: "production"
    team: "platform"

  # Optional: Networking configuration
  # Specify either networkId (simple) OR nicIds (advanced), not both
  networking:
    # Simple variant: Attach to a single network
    networkId: "770e8400-e29b-41d4-a716-446655440000"
    # Advanced variant: Use pre-created NICs (uncomment to use instead of networkId)
    # nicIds:
    #   - "880e8400-e29b-41d4-a716-446655440000"
    #   - "990e8400-e29b-41d4-a716-446655440000"

  # Optional: Security groups to apply to the server
  # If not specified, the project's default security group will be used
  securityGroups:
    - "default"
    - "web-servers"

  # Optional: Cloud-init user data for VM bootstrapping
  # Can be used to override/customize Secret.userData for this specific MachineClass
  # If specified, takes precedence over Secret.userData
  # Note: Secret.userData is typically required by MCM for node bootstrapping
  # Use this to add MachineClass-specific customizations
  userData: |
    #cloud-config
    runcmd:
      - echo "Machine bootstrapped via ProviderSpec"
      - apt-get update

secretRef:
  name: test-secret
  namespace: default

---
# Example: Minimal configuration (only required fields)
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: minimal-mc
  namespace: default
providerSpec:
  machineType: "c1.2"
  imageId: "550e8400-e29b-41d4-a716-446655440000"
secretRef:
  name: test-secret
  namespace: default

---
# Example: Machine with custom cloud-init userData (overrides Secret)
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: custom-userdata-mc
  namespace: default
providerSpec:
  machineType: "c1.2"
  imageId: "550e8400-e29b-41d4-a716-446655440000"
  # UserData in ProviderSpec overrides Secret.userData
  # Useful for MachineClass-specific bootstrapping (e.g., different software per class)
  # Make sure this still includes necessary bootstrap commands for node registration!
  userData: |
    #cloud-config
    package_update: true
    package_upgrade: true
    packages:
      - docker.io
      - kubectl
    runcmd:
      - systemctl enable docker
      - systemctl start docker
      - echo "Custom initialization complete"
      # Include MCM bootstrap commands here if overriding Secret.userData
secretRef:
  name: test-secret
  namespace: default

---
# Example: Machine with custom boot volume configuration
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: custom-bootvolume-mc
  namespace: default
providerSpec:
  machineType: "c1.2"
  imageId: "550e8400-e29b-41d4-a716-446655440000"
  # BootVolume allows fine-grained control over boot disk
  bootVolume:
    # Size in GB (must be >= image size)
    size: 100
    # Performance class: "standard", "premium", etc.
    performanceClass: "premium"
    # Delete volume when server is terminated (default: true)
    # deleteOnTermination: false  # Set to false to preserve boot volume
    # Source: create boot volume from image/snapshot/volume
    # If not specified, uses imageId from ProviderSpec
    # source:
    #   type: "snapshot"  # or "image" or "volume"
    #   id: "770e8400-e29b-41d4-a716-446655440000"
secretRef:
  name: test-secret
  namespace: default

---
# Example: Machine with additional data volumes
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: with-volumes-mc
  namespace: default
providerSpec:
  machineType: "c1.2"
  imageId: "550e8400-e29b-41d4-a716-446655440000"
  # Volumes: attach existing volumes by UUID
  # These are data volumes in addition to the boot disk
  volumes:
    - "880e8400-e29b-41d4-a716-446655440000"  # data-volume-1
    - "990e8400-e29b-41d4-a716-446655440001"  # data-volume-2
secretRef:
  name: test-secret
  namespace: default

---
# Example: Machine with both custom boot volume and additional volumes
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: full-storage-mc
  namespace: default
providerSpec:
  machineType: "c1.2"
  imageId: "550e8400-e29b-41d4-a716-446655440000"
  # Custom boot volume configuration
  bootVolume:
    size: 50
    performanceClass: "standard"
  # Additional data volumes
  volumes:
    - "880e8400-e29b-41d4-a716-446655440000"
secretRef:
  name: test-secret
  namespace: default