apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: default
type: Opaque
stringData:
  # STACKIT project ID (UUID format)
  projectId: "12345678-1234-1234-1234-123456789012"

  # STACKIT Service Account Key (JSON format)
  # Obtain from STACKIT Portal: Project Settings -> Service Accounts -> Create Key
  serviceAccountKey: |
    {
      "credentials": {
        "iss": "service-account-email@sa.stackit.cloud",
        "sub": "uuid-of-service-account",
        "aud": "stackit"
      },
      "privateKey": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
    }

  # STACKIT region (required by SDK v1.0.0+)
  # Valid regions: eu01-1, eu01-2, etc.
  region: "eu01-1"

  # Cloud-init user data for VM bootstrapping
  userData: |
    #cloud-config
    runcmd:
      - echo "Machine bootstrapped"
