apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: default
type: Opaque
stringData:
  # STACKIT project ID (UUID format)
  projectId: "12345678-1234-1234-1234-123456789012"

  # STACKIT API authentication token
  stackitToken: "your-stackit-api-token-here"

  # Cloud-init user data for VM bootstrapping
  userData: |
    #cloud-config
    runcmd:
      - echo "Machine bootstrapped"
