apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: default
type: Opaque
stringData:
  # Required: STACKIT project ID
  projectId: "12345678-1234-1234-1234-123456789012"

  # Required: Cloud-init user data for VM bootstrapping
  # This script runs when the VM first starts
  userData: |
    #cloud-config
    runcmd:
      - echo "Machine bootstrapped"
      # Add your VM initialization commands here